/*
 *  File: ScriptNames.h
 *  Copyright (c) 2024 Sinflower
 *
 *  MIT License
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 *
 */

#pragma once

#include <string>
#include <vector>

static const std::vector<std::wstring> SCRIPT_NAMES = {
	L"attack\\attack_commonbattle.js",
	L"attack\\attack_core.js",
	L"attack\\attack_easybattle.js",
	L"attack\\attack_flow.js",
	L"attack\\attack_order.js",
	L"attack\\attack_pre.js",
	L"attack\\attack_realbattle.js",
	L"base\\base-listcommand.js",
	L"base\\base-objects.js",
	L"base\\base-scrollbar.js",
	L"base\\base-top.js",
	L"constants\\constants-enumeratedtype.js",
	L"eventcommand\\eventcommand-backgroundchange.js",
	L"eventcommand\\eventcommand-bonuschange.js",
	L"eventcommand\\eventcommand-chaptershow.js",
	L"eventcommand\\eventcommand-choiceshow.js",
	L"eventcommand\\eventcommand-classchange.js",
	L"eventcommand\\eventcommand-damagehit.js",
	L"eventcommand\\eventcommand-durabilitychange.js",
	L"eventcommand\\eventcommand-experienceplus.js",
	L"eventcommand\\eventcommand-forcebattle.js",
	L"eventcommand\\eventcommand-goldchange.js",
	L"eventcommand\\eventcommand-hprecovery.js",
	L"eventcommand\\eventcommand-infowindow.js",
	L"eventcommand\\eventcommand-itemchange.js",
	L"eventcommand\\eventcommand-itemuse.js",
	L"eventcommand\\eventcommand-locationfocus.js",
	L"eventcommand\\eventcommand-mapposchoose.js",
	L"eventcommand\\eventcommand-mapposoperation.js",
	L"eventcommand\\eventcommand-messagescroll.js",
	L"eventcommand\\eventcommand-messageshow.js",
	L"eventcommand\\eventcommand-messageterop.js",
	L"eventcommand\\eventcommand-messagetitle.js",
	L"eventcommand\\eventcommand-parameterchange.js",
	L"eventcommand\\eventcommand-savecall.js",
	L"eventcommand\\eventcommand-scriptexecute.js",
	L"eventcommand\\eventcommand-skillchange.js",
	L"eventcommand\\eventcommand-stillmessage.js",
	L"eventcommand\\eventcommand-trophychange.js",
	L"eventcommand\\eventcommand-unitallcommand.js",
	L"eventcommand\\eventcommand-unitfusion.js",
	L"eventcommand\\eventcommand-unitmetamorphoze.js",
	L"eventcommand\\eventcommand-unitslide.js",
	L"eventcommand\\eventcommand-unitstateaddition.js",
	L"executive\\executive-eventcommandcontroller.js",
	L"executive\\executive-eventcommandmanager.js",
	L"executive\\executive-outsidemanager.js",
	L"executive\\executive-scenemanager.js",
	L"executive\\executive-screencontroller.js",
	L"executive\\executive-scriptcall.js",
	L"item\\item-base.js",
	L"item\\item-classchange.js",
	L"item\\item-damage.js",
	L"item\\item-doping.js",
	L"item\\item-durability.js",
	L"item\\item-entirecovery.js",
	L"item\\item-fusion.js",
	L"item\\item-key.js",
	L"item\\item-metamorphoze.js",
	L"item\\item-quick.js",
	L"item\\item-recovery.js",
	L"item\\item-rescue.js",
	L"item\\item-resurrection.js",
	L"item\\item-skillchange.js",
	L"item\\item-state.js",
	L"item\\item-staterecovery.js",
	L"item\\item-steal.js",
	L"item\\item-switch.js",
	L"item\\item-teleportation.js",
	L"item\\item-unusable.js",
	L"map\\map-cource.js",
	L"map\\map-enemyturn.js",
	L"map\\map-enemyturnai.js",
	L"map\\map-mapcommand.js",
	L"map\\map-mapeditor.js",
	L"map\\map-playerturn.js",
	L"map\\map-turnchange.js",
	L"map\\map-unitcommand.js",
	L"scene\\scene-battleresult.js",
	L"scene\\scene-battlesetup.js",
	L"scene\\scene-ending.js",
	L"scene\\scene-eventtest.js",
	L"scene\\scene-freearea.js",
	L"scene\\scene-gameover.js",
	L"scene\\scene-rest.js",
	L"scene\\scene-title.js",
	L"screen\\screen-communication.js",
	L"screen\\screen-config.js",
	L"screen\\screen-experiencedistribution.js",
	L"screen\\screen-extra.js",
	L"screen\\screen-imagetalk.js",
	L"screen\\screen-itemuse.js",
	L"screen\\screen-loadsave.js",
	L"screen\\screen-marshal.js",
	L"screen\\screen-multiclasschange.js",
	L"screen\\screen-objective.js",
	L"screen\\screen-quest.js",
	L"screen\\screen-recollection.js",
	L"screen\\screen-resurrection.js",
	L"screen\\screen-shop.js",
	L"screen\\screen-shoplist.js",
	L"screen\\screen-skill.js",
	L"screen\\screen-stockitemtrade.js",
	L"screen\\screen-support.js",
	L"screen\\screen-switch.js",
	L"screen\\screen-talkcheck.js",
	L"screen\\screen-unititemtrade.js",
	L"screen\\screen-unitmenu.js",
	L"screen\\screen-unitsortie.js",
	L"screen\\screen-unitsummary.js",
	L"screen\\screen-variable.js",
	L"singleton\\singleton-calculator.js",
	L"singleton\\singleton-currentmap.js",
	L"singleton\\singleton-customcharchip.js",
	L"singleton\\singleton-fusioncontrol.js",
	L"singleton\\singleton-inputcontrol.js",
	L"singleton\\singleton-itemcontrol.js",
	L"singleton\\singleton-mouse.js",
	L"singleton\\singleton-paramgroup.js",
	L"singleton\\singleton-rendercontrol.js",
	L"singleton\\singleton-skillcontrol.js",
	L"singleton\\singleton-statecontrol.js",
	L"singleton\\singleton-struct.js",
	L"singleton\\singleton-system.js",
	L"singleton\\singleton-unitlist.js",
	L"singleton\\singleton-wrapper.js",
	L"utility\\utility-anime.js",
	L"utility\\utility-commandlayout.js",
	L"utility\\utility-counter.js",
	L"utility\\utility-cursor.js",
	L"utility\\utility-damagepopup.js",
	L"utility\\utility-dictionaryscrollbar.js",
	L"utility\\utility-event.js",
	L"utility\\utility-messageanalyze.js",
	L"utility\\utility-messageblend.js",
	L"utility\\utility-messageview.js",
	L"utility\\utility-object.js",
	L"utility\\utility-panel.js",
	L"utility\\utility-posselector.js",
	L"utility\\utility-scroll.js",
	L"utility\\utility-scrolltextview.js",
	L"utility\\utility-skill.js",
	L"utility\\utility-trophy.js",
	L"window\\window-info.js",
	L"window\\window-iteminfo.js",
	L"window\\window-itemlist.js",
	L"window\\window-question.js",
	L"window\\window-skillinfo.js",
	L"window\\window-status.js",
	L"window\\window-unitselect.js",
	L"window\\window-unitsentence.js",
	L"window\\window-unitsimple.js",
	L"window\\windowmanager-discard.js",
	L"window\\windowmanager-itemselectmenu.js",
	L"window\\windowmanager-posmenu.js",
	L"window\\windowmanager-weaponselectmenu.js"
};
